services:
  nostream:
    build: .
    container_name: nostream
    environment:
      SECRET: ${SECRET}
      RELAY_PORT: 8008
      # Master
      NOSTR_CONFIG_DIR: /home/node/.nostr

      DB_HOST: ${RDS_HOST}
      DB_PORT: ${RDS_PORT}
      DB_USER: ${RDS_USER}
      DB_PASSWORD: ${RDS_PASSWORD}
      DB_NAME: ${RDS_DB_NAME}
      DB_MIN_POOL_SIZE: 16
      DB_MAX_POOL_SIZE: 64
      DB_ACQUIRE_CONNECTION_TIMEOUT: 60000
      # Read Replica
      READ_REPLICAS: 2
      READ_REPLICA_ENABLED: 'false'
      # Redis
      REDIS_HOST: nostream-cache
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: nostr_ts_relay
      TOR_HOST: tor_proxy
      TOR_CONTROL_PORT: 9051
      TOR_PASSWORD: nostr_ts_relay
      HIDDEN_SERVICE_PORT: 80
      # Payments Processors
      ZEBEDEE_API_KEY: ${ZEBEDEE_API_KEY}
      NODELESS_API_KEY: ${NODELESS_API_KEY}
      NODELESS_WEBHOOK_SECRET: ${NODELESS_WEBHOOK_SECRET}
      OPENNODE_API_KEY: ${OPENNODE_API_KEY}
      LNBITS_API_KEY: ${LNBITS_API_KEY}
    user: node:node
    volumes:
      - ${PWD}/.nostr:/home/node/.nostr
    ports:
      - 0.0.0.0:8008:8008
    depends_on:
      nostream-cache:
        condition: service_healthy
      nostream-migrate:
        condition: service_completed_successfully
    restart: always
    networks:
      default:

  nostream-cache:
    image: redis:7.0.5-alpine3.16
    container_name: nostream-cache
    volumes:
      - cache:/data
    command: redis-server --loglevel warning --requirepass nostr_ts_relay
    networks:
      default:
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping', '|', 'grep', 'PONG']
      interval: 1s
      timeout: 5s
      retries: 5

  nostream-migrate:
    image: node:18-alpine3.16
    container_name: nostream-migrate
    environment:
      DB_HOST: ${RDS_HOST}
      DB_PORT: ${RDS_PORT}
      DB_USER: ${RDS_USER}
      DB_PASSWORD: ${RDS_PASSWORD}
      DB_NAME: ${RDS_DB_NAME}
    entrypoint:
      - sh
      - -c
      - 'cd code && npm install --no-save --quiet knex@2.4.0 pg@8.8.0 && npx knex migrate:latest'
    volumes:
      - ./migrations:/code/migrations
      - ./knexfile.js:/code/knexfile.js
    depends_on:
      nostream-cache:
        condition: service_healthy
    networks:
      default:

networks:
  default:
    name: nostream
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24

volumes:
  cache:
